### ISSUE TITLE
Discussion: Should we move to a monorepo?

### ISSUE THREAD

**Issue by koonpeng** [osrf/romi-dashboard#123]
With the ongoing work at https://github.com/osrf/romi-js-api-server, there is now a package that is closely linked with romi-dashboard. A monorepo will make testing and releasing easier.

Suppose if we decide to go monorepo, which related repo should we merge together? romi-dashboard and romi-js-api-server is a given, other less related repos are
* romi-js-core-interfaces
* romi-js-soss-transport
* romi-js-rclnodejs-transport

We don't use romi-js-soss-transport but it is closely tied in with romi-js-core-interfaces.

Depending on what repo we merge together, we need a suitable name or the new monorepo as well.

**Comment by matiasbavera** [comment]
> Suppose if we decide to go monorepo, which related repo should we merge together? romi-dashboard and romi-js-api-server is a given, other less related repos are

Just to check when we talk about monorepo. Do you mean that we are going to delete all those repos and we are going to create only one with all those projects?
Or we would add thirdParties like what we did here https://github.com/osrf/romi-js-core-interfaces

For the first case
Actually, I would choose just these two `romi-dashboard` and` romi-js-api-server` or all of them. I'm afraid that if we choose all of them, when someone else has to implement something similar in another project, they won't be able to reuse the code or not even find it since it will be inside a giant repo. From what I understand we would not be maintaining two repos in parallel either. But if all these projects have exclusive use for Romi project and they are hardly going to be used for other projects, I think that making a monorepo will only bring us benefits.

**Comment by ChawinTan** [comment]
> Just to check when we talk about monorepo. Do you mean that we are going to delete all those repos and we are going to create only one with all those projects?
> Or we would add thirdParties like what we did here https://github.com/osrf/romi-js-core-interfaces

I had the same question. My first impression of a mono repo is `romi-dashboard` + `romi-js-api-server` as the rest of the modules are meant to dependencies that needs to be installed? 

Base on my rather shallow understanding of how the system works, I was leaning to the idea that `romi-js-core-interfaces`, `romi-js-soss-transport` and `romi-js-rclnodejs-transport` will be grouped together to form one unified package since they are required for `romi-dashboard` to work.

**Comment by koonpeng** [comment]
here is an example of a monorepo https://github.com/facebook/react/tree/master/packages.

The main difference is that instead of one repo = one package, a monorepo just combines multiple packages in one repo. They will all still be released as individual packages, and you will usually use `npm link` when developing to automatically reference the local packages. lerna is a popular tool to manage such repos.

A monorepo has the advantages that it makes cross package testing much easier, a quick search on monorepo vs polyrepo should give good explanations of their pros and cons, ultimately it comes down to how tightly coupled the packages are, in the case of dashboard and api server, it makes alot of sense to put them together. The other packages however are less couple and may be better off separated.

**Comment by matiasbavera** [comment]
> here is an example of a monorepo https://github.com/facebook/react/tree/master/packages.
> 
> The main difference is that instead of one repo = one package, a monorepo just combines multiple packages in one repo. They will all still be released as individual packages, and you will usually use `npm link` when developing to automatically reference the local packages. lerna is a popular tool to manage such repos.

Thanks for this! 



> The other packages however are less couple and may be better off separated.

+1 to this

**Comment by matiasbavera** [comment]
I think we can close this @koonpeng
