### ISSUE TITLE
Negotiations UI improvements

### ISSUE THREAD

**Issue by matiasbavera** [osrf/romi-dashboard#126]
* Place a separator between the conflicts.
* Make the tree levels difference more noticeable. Either by colors or by bold or by putting an explicit indentation.
* When pressing in a negotiation on the panel, mark or distinguish which is the selected negotiation.

* Add a button to clear the map of the selected negotiations and clear the selected negotiation on the panel. We now have a button that makes all the negotiations disappear or show but not just a particular trajectory 
![image](https://user-images.githubusercontent.com/11761240/94496029-4a316880-01c1-11eb-9dc7-1cec10e9b385.png)

**Comment by ChawinTan** [comment]
![Reddit_inspired_negotiations](https://user-images.githubusercontent.com/29136440/95565254-7c10bd80-0a52-11eb-9a95-f640f815e0ee.png)

So here's my attempt at beautifying the negotiations panel, inspiration taken superficially from reddit. Instead of placing a separator, I used a vertical border to indicate the contents of a particular tree and children trees. 

Apart from that, I added some paddings, border styling and removed the `selected` stylings to ensure that only the contents have the background color. Is the `selected` styles needed?



> * When pressing in a negotiation on the panel, mark or distinguish which is the selected negotiation.

I think removing the `selected` stylings does the job as the selected negotiation is now  a different color from the background.

> * Add a button to clear the map of the selected negotiations and clear the selected negotiation on the panel. We now have a button that makes all the negotiations disappear or show but not just a particular trajectory

You mean to have the following buttons?:

- A button to clear all the current negotiations on the panel
- Another button to clear the currently selected negotiation? Sort of like a reset.

**Comment by matiasbavera** [comment]
> ![Reddit_inspired_negotiations](https://user-images.githubusercontent.com/29136440/95565254-7c10bd80-0a52-11eb-9a95-f640f815e0ee.png)
> 
> So here's my attempt at beautifying the negotiations panel, inspiration taken superficially from reddit. Instead of placing a separator, I used a vertical border to indicate the contents of a particular tree and children trees.
> 
> Apart from that, I added some paddings, border styling and removed the `selected` stylings to ensure that only the contents have the background color. Is the `selected` styles needed?

Oh man! this looks good! =) What do you think if we reduce a bit the vertical space between the boxes? in order to see as many negotiations as possible before start scrolling. 



> I think removing the `selected` stylings does the job as the selected negotiation is now a different color from the background.
> 
> >

Is the gray the selected one, right? Looks good.



> You mean to have the following buttons?:
> 
> * A button to clear all the current negotiations on the panel
> * Another button to clear the currently selected negotiation? Sort of like a reset.

Yeah, you got it.

**Comment by koonpeng** [comment]
> ![Reddit_inspired_negotiations](https://user-images.githubusercontent.com/29136440/95565254-7c10bd80-0a52-11eb-9a95-f640f815e0ee.png)
> 
> So here's my attempt at beautifying the negotiations panel, inspiration taken superficially from reddit. Instead of placing a separator, I used a vertical border to indicate the contents of a particular tree and children trees.
> 
> Apart from that, I added some paddings, border styling and removed the `selected` stylings to ensure that only the contents have the background color. Is the `selected` styles needed?
> 
> > * When pressing in a negotiation on the panel, mark or distinguish which is the selected negotiation.
> 
> I think removing the `selected` stylings does the job as the selected negotiation is now a different color from the background.
> 
> > * Add a button to clear the map of the selected negotiations and clear the selected negotiation on the panel. We now have a button that makes all the negotiations disappear or show but not just a particular trajectory
> 
> You mean to have the following buttons?:
> 
> * A button to clear all the current negotiations on the panel
> * Another button to clear the currently selected negotiation? Sort of like a reset.

:+1: . Rounded borders is the secret sauce to make everything look good. Also shadows.

imo we can remove the "Negotation Trajectories" in the leaflet layers, since that is implied to be on when you are on the negotation panel, and off otherwise. I don't see a situation where you would want to toggle it manually.

**Comment by ChawinTan** [comment]
merged
