### ISSUE TITLE
More testing (code coverage goal)

### ISSUE THREAD

**Issue by koonpeng** [osrf/romi-dashboard#128]
Let's make it a target to hit a certain amount of code coverage. Anyone have a suggestion of a good target? How does 80% sound?

**Comment by ChawinTan** [comment]
80% sounds like a good target to hit first. We can try something higher later if we are more ambitious. Will it be 80% for every file or  for the entire project?

**Comment by ddengster** [comment]
I'd be very wary of putting arbitrary numbers as targets; people will jump arbitrary hoops and the concessions we make to cater to to this will make make your lives miserable.

That said, I'd recommend testing the critical features like making sure robots receive commands properly. Then do additional tests for hard/cubersome/rare to reproduce cases.

**Comment by koonpeng** [comment]
> 80% sounds like a good target to hit first. We can try something higher later if we are more ambitious. Will it be 80% for every file or for the entire project?

It would be for the whole project. I'm not sure for the codecov patch check, maybe it could be lower.

> I'd be very wary of putting arbitrary numbers as targets; people will jump arbitrary hoops and the concessions we make to cater to to this will make make your lives miserable.

Which is why we should choose a target that is not too high that it requires pedantic, useless tests. High coverage doesn't mean well tested code, but low coverage does mean there are insufficient tests. For developers, the coverage is helpful to find which parts of the code is not tested, for maintainers/reviewers it's helpful to filter out badly tested code from getting merged. This is not a hard limit for the coverage requirements, but more of a general guideline on the level of code quality we want to target.

**Comment by ddengster** [comment]
> This is not a hard limit for the coverage requirements, but more of a general guideline on the level of code quality we want to target.

I'd question the assumption that equates coverage to code quality. The moment we set a number as a target, whether it's a soft or hard one, it will promote ways of writing code to pass the system rather than actually looking at the commit and prescribing tests for it.

**Comment by matiasbavera** [comment]
If I can put my spoon in, the % to be completed of the coverage, in general, is a very controversial topic, and as Edwin said it is a topic to be taken with care, for the reasons already mentioned in this discussion. I totally agree with KP that we need more tests and it is not only to make the codevot happy but to alleviate the technical debt we have with that. However, I believe that the two have a point in common, not to write useless tests, because, in the end, it is one more thing to maintain.

There is something I want to ask, where do we draw the line to say that tests are useless, what style of tests we hope to see in PRs. I'm asking this because in some projects only "useful" tests (edge ​​cases) are accepted for maintainability reasons. In our particular case, I think it is worth looking not only at the edge cases but also at the expected behavior of components in various situations (as we are doing now).

I understand the % coverage can be completed with tests of the expected behavior of the components (and that's the why of Edwin's comment `coverage != code Quality`) so the edge cases would no longer be part of the coverage, I think that's where the reviewer comes in, to try to ask for those cases to be tested.

And this is my subjective opinion on the subject, I think that the tests are very useful for the reviewers because they let the reviewers know what the programmer was thinking at the time of doing things.

As Edwin said, I think we can continue with the 80% coverage, but taking into account the points mentioned above and of course without the pressure of having to do the wrong things to please codevot.

Also here are a few papers that are about the relation between test_coverage and code Quality.

* https://www.researchgate.net/publication/299594922_Is_Code_Quality_Related_to_Test_Coverage
* https://ieeexplore.ieee.org/document/902502?arnumber=902502

HTH,

**Comment by ddengster** [comment]
> As Edwin said, I think we can continue with the 80% coverage, but taking into account the points mentioned above and of course without the pressure of having to do the wrong things to please codebot.

To clarify, I'd actually do away with the number as a target.

To supplement this discussion with a worst case scenario, say you have a PR adding in code related to talking to the backend servers. Codecov then reports 0% coverage (unit tests dont cover backend talk) and the reviewer says 'add more tests' upon seeing the % without looking. Now the PR submitter can take this a few ways: 1) trying to do that mocking class thing (which is more code to maintain) or 2) stalling. Now the reviewer can choose to stall for the simple reason of not hitting the target number.

> Also here are a few papers that are about the relation between test_coverage and code Quality.

The metrics used in these papers are very subjective and can be misleading - they talk about the code-to-person communication aspects of the codebase, but not the software quality that matters (ie. bugs, weird case scenarios). And I generally believe that these code-to-person communication aspects can be overcome thanks to the adaptability of the human brain and because I've worked in codebases that break their prescribed metrics and still feel great to work in.

**Comment by koonpeng** [comment]
I suggest we move this discussion to slack.
