### ISSUE TITLE
Locations for loop and delivery requests

### ISSUE THREAD

**Issue by koonpeng** [osrf/romi-dashboard#54]
Mock places are currently used, we need to come up with a solution for it.

Afaik the current state is that different fleet can have access to different locations, but there is no way to find the list of valid locations for each fleet.

**Comment by baviera08** [comment]
Yeah! you're right.

This is the information that I have (CC: @Yadunund ):

The start_name and finish_name of the Loop request should contain valid waypoint names as listed in BuildingMap->levels->nav_graphs[i]->vertices[j]->name. However as there is no public mapping between the nav_graph index (i) and the fleet name, it is not possible to know which fleet of robots uses which nav graph from the BuildingMap msg. 

BuildingMap->levels->places is not currently populated. The use of places is kind of deprecated. The information of locations that a robot can travel to is stored as a GraphNode in BuildingMap->levels->nav_graphs[i]->vertices. This is because there are named waypoints that Robot A can travel to but not Robot B. Hence, having named Places per level is ambiguous. 

We also need to know the exiting dispensers on each place (for the delivery request).

QQ: Are the places available to one fleet, should always be available? I mean what happens if one place its unavailable due to a problem. If we send that information through the BuildingMap that will not be updated later right? (please correct me if I'm wrong).

On the UI:
When we can get that information, we can parse it, load it at the system startup to a React context hook to make it accessible from multiple components.
