### ISSUE TITLE
Robot icons

### ISSUE THREAD

**Issue by koonpeng** [osrf/romi-dashboard#55]
Since we don't know what robots are present, we can't include the icons as part of romi-dashboard. The icon resources needs to be out-of-tree, two possible approach:

  1. A script to tailor a deployment of dashboard with a set of resources.
  2. A resource server that the dashboard downloads at run time.

**Comment by baviera08** [comment]
I think that Op 2 can be a more flexible choice on prod, depending on our design. 
I mean we change the icon of the robot on the production server by changing the icon on the resource server.

**Before**
robot 1: https://pathToResource1.com
robot 2: https://pathToResource2.com || default.

where` resource1=iconA` and `resouce2=null`

**After**
`resource1=iconC` and `resouce2=iconD`

Setting up a resource server will be an extra step for the development time though. But I think we can find a workaround for that. We can set like a system variable to use some generated svg icons (like the one we have now) for dev and the URL of the icon on prod.

QQ: Will the icons be different in each company that will deploy and use the system?

**Comment by koonpeng** [comment]
> QQ: Will the icons be different in each company that will deploy and use the system?

Yes, as each deployment of rmf will have different robots, it would be up to the vendor to provide icons for their robots.

---

Since this is a webapp, both options should allow us to update the resources without user intervention. We probably still need the generated icons we have now as maybe not all robots will have icons available. We can have a json file that maps the robot model to the path of its icon, the dashboard will download this json and parses it at the start. Or we just have the dashboard attempt to download the icons at a predefined path and fallback to the svg icons if it fails.

The main difference is that with Option 1 we have a same domain request and with Option 2 we have a cross origin request. Option 1 may have some advantage when it comes to caching, I'm not sure how caching works for external resources and how to keep them updated.

**Comment by baviera08** [comment]
Yeah, you're right about the cross-origin. About the cache, it works almost the same way, we will need to add [cache headers](https://stackoverflow.com/questions/40541643/how-do-i-cache-remote-images), and we will need to work with cache invalidation. Mmmhh.. yeah for this problem I don't think it worth it. We can go with the first option. We can serve images from the project itself (from the public folder). We can set the path according to the robot model, e.g: 
* public/model1/model1.png; 
* public/model2/model2.png;
or
* public/fleet/model.png; 

and as a fallback, we can assign it a default SVG logo.
 
But thinking on the big picture, do we want to store and display on Romi Dashboard files like pdf, images, icons, etc. from the users? E.g: Screenshot of problems, photos of situations, report of problems?. I'm asking this because it may be convenient to use a High-Performance Object Storage like https://github.com/minio/minio to handle things like this.

For the last option, it makes total sense to me to have a JSON file that maps the robot model to the URL of its icon (provided by the object storage), and the dashboard should be able to download this JSON and parses it at the start.

What do you think about it? 

CC: @Yadunund

**Comment by koonpeng** [comment]
> But thinking on the big picture, do we want to store and display on Romi Dashboard files like pdf, images, icons, etc. from the users? E.g: Screenshot of problems, photos of situations, report of problems?. I'm asking this because it may be convenient to use a High-Performance Object Storage like https://github.com/minio/minio to handle things like this.

A feedback system would be interesting, but there's no plan for that now yet. I doubt we would ever reach a scale where minIO would bring any advantage but I'm not against using it if it's easy to setup and maintain.

**Comment by baviera08** [comment]
Great, I just wanted to make sure of that. We can go with option 1 if we would never reach a scale where minIO would bring any advantage =).

PS: it's not difficult to set up and maintain, but we will need to add extra components to the final architecture (databases, maybe a middleware, etc)

**Comment by baviera08** [comment]
Created from this Issue:
* https://github.com/osrf/romi-dashboard/issues/63
* https://github.com/osrf/romi-dashboard/issues/62

**Comment by matiasbavera** [comment]
Implemented in https://github.com/osrf/romi-dashboard/pull/66
