### ISSUE TITLE
Warn about conflicting trajectories between robots

### ISSUE THREAD

**Issue by matiasbavera** [osrf/romi-dashboard#9]
Create an alert when two robots have a conflicting trajectory (this alert could disappear automatically after some time)

Mark the as red the path and robot that has conflicting trajectories. 

Nice to have:
We can also make the robot bigger too when it has conflicting trajectories.

**Comment by baviera08** [comment]
If possible we should test this on the new “participant system”:
* rmf_core: develop 
* rmf_scheduler_visualizer: develop 

We should test that way because the old system does not produce the time of the conflict. Ideally we want to show the exact point of conflict instead of making the world path red. This goes in line with a separate improvement that customizes the trajectory based on the robot (different colors/patterns) to allow the trajectories to be easily differentiated when there are large amounts of robots in the system.

**Comment by baviera08** [comment]
* I did not find a way to set the color to the robot when it has a conflicting path. Because te robot and trajectory have independent messages. The idea here was to make the robot bigger and change its color when it has path conflicts.

**Comment by cnboonhan94** [comment]
https://cgh.webex.com/meet/CT_CHART
